name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - richardo2016
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.12.x(Latest)
        - 1.11.x
        - 1.10.x
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: What Systems are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: dropdown
    id: arch
    attributes:
      label: What Arch are you seeing the problem on?
      multiple: true
      options:
        - x64(amd64)
        - x86(i386)
        - arm
        - armv6
        - arm64
        # - mips
        # - mips64
    validations:
      required: true
  - type: textarea
    id: detailed_enviroment
    attributes:
      label: Enviroment Information
      description: |
        besides **Systems**, You may provide more details about your runtime environment, such as
        - Linux release type (Debian, Ubuntu, alpine...)
        - Windows Version(7, 8, 10...)
        - hardware info
        - fibjs version (0.33.x, 0.34.x...)
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
