version: "3.7"
services:
  db5.6:
    image: mysql:5.6
    restart: always
    ports:
      - "3356:3306"
    volumes:
      - "db_data:/var/lib/mysql5.6"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=fxjs-orm-test
  db5.7:
    image: mysql:5.7
    restart: always
    ports:
      - "3357:3306"
    volumes:
      - "db_data:/var/lib/mysql5.7"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=fxjs-orm-test
  db8.0:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3380:3306"
    volumes:
      - "db_data:/var/lib/mysql8.0"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=fxjs-orm-test

volumes:
  db_data: null